version: "{build}"

os: Windows Server 2012 R2

platform:
  - x86
  - x64

environment:
  nodejs_version: "8.9.3"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm
  - npm install
  - .\bin\npm.cmd test

build: off

test: off

deploy: off
