version: "{build}"

os: Windows Server 2012 R2

platform:
  - x86
  - x64

environment:
  nodejs_version: "8.9.3"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

build_script:
  - npm install

test_script:
  - .\bin\npm.cmd test

deploy: off

branches:
  only:
  - master
